"""S4 tool runtime — typed pipeline around ``ToolRegistry``.

Pipeline: validate → permission → run → persist → artifact (auto-spill).

Public surface:

- :class:`ToolError`, :class:`ToolResult`, :class:`ArtifactRef` — typed
  return values used by the new executor.
- :class:`ToolRuntime` — the orchestrator. ``ToolRuntime.execute`` returns
  a :class:`ToolResult`; large outputs are spilled to ``tool_artifacts``
  and the model receives a compact reference JSON.
- :func:`load_permission_policy` / :class:`PermissionPolicy` — yaml-driven
  policy used by tool execution and approval handling.
"""

from __future__ import annotations

from .catalog import (
    RUNTIME_TOOL_CONTEXT,
    BuildChatgptXhsPromptArgs,
    ChatgptDownloadLatestImagesArgs,
    ChatgptExtractLatestTextArgs,
    ChatgptOpenArgs,
    ChatgptSaveArtifactsArgs,
    ChatgptSendMessageArgs,
    ChatgptWaitUntilDoneArgs,
    CheckXhsContentRiskArgs,
    ContextPactUpdateArgs,
    CreateAgentTeamArgs,
    CreateXhsContentJobArgs,
    DelegateTaskArgs,
    ListLocalDirectoryArgs,
    ListWorkspaceArgs,
    ReadLocalFileArgs,
    ReadWorkspaceFileArgs,
    RunAgentWorkflowArgs,
    RunShellCommandArgs,
    SkillProposeArgs,
    ToolRegistry,
    ValidateXhsNoteJsonArgs,
    WebSearchArgs,
    WriteLocalFileArgs,
    XhsFillBodyArgs,
    XhsFillHashtagsArgs,
    XhsFillTitleArgs,
    XhsJobArgs,
    XhsOpenCreatorArgs,
    XhsUploadImagesArgs,
    build_chatgpt_xhs_prompt,
    chatgpt_download_latest_images,
    chatgpt_extract_latest_text,
    chatgpt_new_chat,
    chatgpt_open,
    chatgpt_save_artifacts,
    chatgpt_send_message,
    chatgpt_wait_until_done,
    check_xhs_content_risk,
    context_pact_update,
    create_agent_team,
    create_default_registry,
    create_xhs_content_job,
    delegate_task,
    get_current_time,
    list_local_directory,
    list_workspace,
    read_local_file,
    read_workspace_file,
    run_agent_workflow,
    run_shell_command,
    skill_propose,
    validate_xhs_note_json,
    web_search,
    write_local_file,
    xhs_fill_body,
    xhs_fill_hashtags,
    xhs_fill_title,
    xhs_open_creator,
    xhs_start_note,
    xhs_stop_before_publish,
    xhs_take_preview_screenshot,
    xhs_upload_images,
)
from .executor import (
    ARTIFACT_SPILL_THRESHOLD,
    ToolRuntime,
    make_tool_runtime,
)
from .permissions import (
    PermissionDecision,
    PermissionPolicy,
    default_permission_policy,
    load_permission_policy,
)
from .result import (
    ArtifactRef,
    ToolError,
    ToolErrorCode,
    ToolResult,
)

__all__ = [
    "ARTIFACT_SPILL_THRESHOLD",
    "ArtifactRef",
    "BuildChatgptXhsPromptArgs",
    "ChatgptDownloadLatestImagesArgs",
    "ChatgptExtractLatestTextArgs",
    "ChatgptOpenArgs",
    "ChatgptSaveArtifactsArgs",
    "ChatgptSendMessageArgs",
    "ChatgptWaitUntilDoneArgs",
    "CheckXhsContentRiskArgs",
    "ContextPactUpdateArgs",
    "CreateAgentTeamArgs",
    "CreateXhsContentJobArgs",
    "DelegateTaskArgs",
    "ListLocalDirectoryArgs",
    "ListWorkspaceArgs",
    "PermissionDecision",
    "PermissionPolicy",
    "RUNTIME_TOOL_CONTEXT",
    "ReadLocalFileArgs",
    "ReadWorkspaceFileArgs",
    "RunShellCommandArgs",
    "RunAgentWorkflowArgs",
    "SkillProposeArgs",
    "ToolError",
    "ToolErrorCode",
    "ToolResult",
    "ToolRuntime",
    "ToolRegistry",
    "ValidateXhsNoteJsonArgs",
    "WebSearchArgs",
    "WriteLocalFileArgs",
    "XhsFillBodyArgs",
    "XhsFillHashtagsArgs",
    "XhsFillTitleArgs",
    "XhsJobArgs",
    "XhsOpenCreatorArgs",
    "XhsUploadImagesArgs",
    "build_chatgpt_xhs_prompt",
    "chatgpt_download_latest_images",
    "chatgpt_extract_latest_text",
    "chatgpt_new_chat",
    "chatgpt_open",
    "chatgpt_save_artifacts",
    "chatgpt_send_message",
    "chatgpt_wait_until_done",
    "check_xhs_content_risk",
    "context_pact_update",
    "create_agent_team",
    "create_default_registry",
    "create_xhs_content_job",
    "default_permission_policy",
    "delegate_task",
    "get_current_time",
    "list_local_directory",
    "list_workspace",
    "load_permission_policy",
    "make_tool_runtime",
    "read_local_file",
    "read_workspace_file",
    "run_shell_command",
    "run_agent_workflow",
    "skill_propose",
    "validate_xhs_note_json",
    "web_search",
    "write_local_file",
    "xhs_fill_body",
    "xhs_fill_hashtags",
    "xhs_fill_title",
    "xhs_open_creator",
    "xhs_start_note",
    "xhs_stop_before_publish",
    "xhs_take_preview_screenshot",
    "xhs_upload_images",
]
